# Copyright (c) PRO-Robotech
# SPDX-License-Identifier: BUSL-1.1

{{- if not .Values.db.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kacho-nlb.dbSecretName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "kacho-nlb.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "db.password is required when db.existingSecret is empty" .Values.db.password | quote }}
{{- end }}
