# Copyright (c) PRO-Robotech
# SPDX-License-Identifier: BUSL-1.1

{{- if .Values.serviceMonitor.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kacho-nlb.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "kacho-nlb.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "kacho-nlb.selectorLabels" . | nindent 6 }}
      kacho.io/listener: public
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace | default .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      path: /metrics
{{- end }}
